### ISSUE TITLE
Error running `yarn`

### ISSUE THREAD

**Issue by timothyjensen** [deliciousbrains/wp-react-boilerplate#2]
Step 5 in the Getting Started section of the Readme says to 
>`cd` into your checked out folder and run `yarn`

When I run `yarn`, however, I get the following error: 
>webpack-dev-server@2.5.1: The engine "node" is incompatible with this module. Expected version ">=4.7".

I tried `yarn --ignore-engines` (ref. https://github.com/akveo/ng2-admin/issues/717#issuecomment-280083261) and so far that seems to work.

**Comment by ptasker** [comment]
Hi @timothyjensen, thanks for logging the issue! What version of Node are you running? Does updating Node to something greater than 4.7 do the trick?

**Comment by timothyjensen** [comment]
Thanks, Peter. I have since updated Node and am not seeing the error any more, so that must have been my problem.

**Comment by ptasker** [comment]
🎉
